name: Creacion de varios artefactos ZIP

on:
  push:
    branches:
      - main4
jobs:
  crear-artefacto-alfa:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Crear directotios alfa
        run: mkdir alfa

      - name: step 2 - Adicionar archivos al directorio alfa
        run: |
          cd alfa
          echo 'Mensaje alfa 1'    > alpha01.html
          echo 'Mensaje alfa 2'    > alpha02.html
          cd ..

      - name: step 3 - Zip Directorio alfa
        run: zip -r alfa.zip alfa
        
      - name: step 4 - Verificacion de la creacion de arefactos ZIP
        run: ls -la 
                
  crear-artefacto-beta:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Crear directotios beta
        run: mkdir beta

      - name: step 2 - Adicionar archivos al directorio beta
        run: |
          cd beta
          echo 'Mensaje beta 1'    > beta01.html
          echo 'Mensaje beta 2'    > beta02.html
          cd ..

      - name: step 3 - Zip Directorio beta
        run: zip -r beta.zip beta
        
      - name: step 4 - Verificacion de la creacion de arefactos ZIP
        run: ls -la 
                
  crear-artefacto-gama:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Crear directotios gama
        run: mkdir gama

      - name: step 2 - Adicionar archivos al directorio gama
        run: |
          cd gama
          echo 'Mensaje gama 1'    > gama01.html
          echo 'Mensaje gama 2'    > gama02.html
          cd ..

      - name: step 3 - Zip Directorio gama
        run: zip -r gama.zip gama
        
      - name: step 4 - Verificacion de la creacion de arefactos ZIP
        run: ls -la        
        

     
