name: Trabajos Dependientes

on:
  push:
    branches:
      - main10
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecución de la configuracion
        run: sh ./setup_server.sh
  build:
    needs: setup  
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecucionn de la compilacion
        run: sh ./build_server.sh
  test:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecucion de las pruebas
        run: sh ./test_server.sh
